






allprojects {

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}



rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            freeCompilerArgs += ["-Xskip-metadata-version-check"]
        }
    }
    tasks.configureEach { task ->
        if (task.name.contains("lintVital") || task.name.contains("LintVital")) {
            task.enabled = false
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
