org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024M
android.useAndroidX=true
android.enableJetifier=false
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=true
# systemProp.http.proxyHost=your_proxy
# systemProp.http.proxyPort=your_port
# systemProp.https.proxyHost=your_proxy
# systemProp.https.proxyPort=your_port

